### ISSUE TITLE
Stay Language 

### ISSUE THREAD

**Issue by jdelacruz2712** [akaunting/language#1]
If I want to stay the language change from the login to the session started and it is kept recurrently despite disconnecting me from the system, as could be done for example I was modifying middleware but I boot in the select a language like unknow

**Comment by jdelacruz2712** [comment]
I have a solution and it is to pass the session of a cookie and with this modify some things in the vendor files

**Comment by jdelacruz2712** [comment]
![image](https://user-images.githubusercontent.com/7109723/34578185-00a78726-f152-11e7-9899-e0983b1579e8.png)

![image](https://user-images.githubusercontent.com/7109723/34578199-0a840e0e-f152-11e7-9828-be50df2363bc.png)

![image](https://user-images.githubusercontent.com/7109723/34578211-1838aa3c-f152-11e7-92a1-21f8e61b0399.png)

![image](https://user-images.githubusercontent.com/7109723/34578229-2c98f7ac-f152-11e7-9463-c77ea683730e.png)

**Comment by denisdulici** [comment]
Can you plz submit a pull request so we could test it?
