### ISSUE TITLE
Problem with Facebook link thumbnail

### ISSUE THREAD

**Issue by ecke101** [akaunting/language#19]
Hello, thanks for this nice script. I had a problem with facebook links where it would give an error message because $code was empty for some reason. This is what I did to fix it (src/Language.php):
`    public static function back($code)
    {
        if (!$code)
            return route('language::back', ['locale' => config('language.allowed')[0]]);
        return route('language::back', ['locale' => $code]);
    }`

**Comment by denisdulici** [comment]
Not sure where do you get this but feel free to send a PR fix.

**Comment by ecke101** [comment]
When putting a link on facebook the facebook servers connect to the site and try to read some info, that is where the error message was.
