### ISSUE TITLE
Class 'Date' not found

### ISSUE THREAD

**Issue by jonasniedermair** [akaunting/language#2]
I can't switch language. I get the following error:
![screenshot_20180123_185753](https://user-images.githubusercontent.com/28958031/35292050-92ee102e-006f-11e8-9465-111db9ea1640.png)

**Comment by jonasniedermair** [comment]
Why is there a \ before Date ? If I comment this line everything works fine..

**Comment by denisdulici** [comment]
It's the Date package: https://github.com/jenssegers/date

You can disable it from config:
https://github.com/akaunting/language/blob/master/src/Config/language.php#L44
