### ISSUE TITLE
seems not compatible with laravel-7

### ISSUE THREAD

**Issue by robov** [akaunting/language#20]
seems not compatible with laravel-7

Problem 1
    - Conclusion: don't install akaunting/language 1.0.13
    - Conclusion: don't install akaunting/language 1.0.12
    - Conclusion: don't install akaunting/language 1.0.11
    - Conclusion: don't install akaunting/language 1.0.10
    - Conclusion: don't install akaunting/language 1.0.9
    - Conclusion: don't install akaunting/language 1.0.8
    - Conclusion: don't install akaunting/language 1.0.7
    - Conclusion: don't install akaunting/language 1.0.6
    - Conclusion: don't install akaunting/language 1.0.5
    - Conclusion: don't install akaunting/language 1.0.4
    - Conclusion: don't install akaunting/language 1.0.3
    - Conclusion: don't install akaunting/language 1.0.2
    - Conclusion: don't install akaunting/language 1.0.1
    - Conclusion: remove laravel/framework v7.0.7
    - Installation request for akaunting/language ^1.0 -> satisfiable by akaunting/language[1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9].
    - Conclusion: don't install laravel/framework v7.0.7

**Comment by denisdulici** [comment]
Released a new version.
