### ISSUE TITLE
Cant change language for logged in user (voyager)

### ISSUE THREAD

**Issue by pabloeh** [akaunting/language#25]
if i change language for a logged in user, i got the error 
`Call to a member function save() on null` on `akaunting\language\src\Controllers\Language.php:32`

Im using Laravel version 7.11.0
PHP version 7.4.0
akaunting/language version 1.0.16
tcg/voyager version 1.4

I think it's related to voyager.
i fixed it by changing `Auth::user()->setAttribute('locale', $locale)->save();` to
`$user = User::find(Auth::user()->id);
            $user->locale = $locale;
            $user->save();`

**Comment by denisdulici** [comment]
Feel free to send a PR.
