### ISSUE TITLE
Auth save issue

### ISSUE THREAD

**Issue by BahaStriker** [akaunting/language#5]
Call to a member function save() on null

`if (Auth::check()) {`
`
            Auth::user()->setAttribute('locale', $locale)->save();
`
`
        } else {
`
`
            $request->session()->put('locale', $locale);
`
`
        }`

The setAttribute is throwing an issue, other than that language switcher works when browsing as guest

please help :c

**Comment by walidbagh** [comment]
Same problem, Need a fix plz

**Comment by walidbagh** [comment]
@BahaStriker @cuneytsenturk 
I fixed this issue by modifying the controller :
`if (Auth::check()) {
            **$user = Auth::user();
            $user->locale = $locale;
            $user->save();**
        } else {
            $request->session()->put('locale', $locale);
        }` 
Hope it gets patched soon. :D

**Comment by BahaStriker** [comment]
Bro thanks for the quick fix, it works

**Comment by denisdulici** [comment]
@walidbagh Feel free to send a pull request please.
